final topMovies100k = [
  {
    "vote_count": 18842,
    "popularity": 38.314,
    "id": 13,
    "video": false,
    "media_type": "movie",
    "vote_average": 8.5,
    "title": "Forrest Gump",
    "release_date": "1994-07-06",
    "original_language": "en",
    "original_title": "Forrest Gump",
    "genre_ids": [35, 18, 10749],
    "backdrop_path": "/7c9UVPPiTPltouxRVY6N9uugaVA.jpg",
    "adult": false,
    "overview":
        "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    "poster_path": "/clolk7rB5lAjs41SD0Vt6IXYLMm.jpg"
  },
  {
    "poster_path": "/5KCVkau1HEl7ZzfPsKAPM0sMiKc.jpg",
    "popularity": 48.068,
    "vote_count": 17103,
    "video": false,
    "media_type": "movie",
    "id": 278,
    "adult": false,
    "backdrop_path": "/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg",
    "original_language": "en",
    "original_title": "The Shawshank Redemption",
    "genre_ids": [80, 18],
    "title": "The Shawshank Redemption",
    "vote_average": 8.7,
    "overview":
        "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    "release_date": "1994-09-23"
  },
  {
    "poster_path": "/plnlrtBUULT0rh3Xsjmpubiso3L.jpg",
    "popularity": 49.075,
    "vote_count": 19491,
    "video": false,
    "media_type": "movie",
    "id": 680,
    "adult": false,
    "backdrop_path": "/52StM7zDmcjeKxWkW55X5LtoLQi.jpg",
    "original_language": "en",
    "original_title": "Pulp Fiction",
    "genre_ids": [80, 53],
    "title": "Pulp Fiction",
    "vote_average": 8.5,
    "overview":
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    "release_date": "1994-09-10"
  },
  {
    "poster_path": "/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
    "popularity": 7.273,
    "vote_count": 10785,
    "video": false,
    "media_type": "movie",
    "id": 274,
    "adult": false,
    "backdrop_path": "/pI9B4wppGflpsOD2T6rxgC5Clmz.jpg",
    "original_language": "en",
    "original_title": "The Silence of the Lambs",
    "genre_ids": [80, 18, 27, 53],
    "title": "The Silence of the Lambs",
    "vote_average": 8.3,
    "overview":
        "Clarice Starling is a top student at the FBI's training academy. Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism. Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
    "release_date": "1991-02-01"
  },
  {
    "vote_count": 17732,
    "popularity": 50.658,
    "id": 603,
    "video": false,
    "media_type": "movie",
    "vote_average": 8.1,
    "title": "The Matrix",
    "release_date": "1999-03-30",
    "original_language": "en",
    "original_title": "The Matrix",
    "genre_ids": [28, 878],
    "backdrop_path": "/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    "adult": false,
    "overview":
        "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    "poster_path": "/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg"
  },
  {
    "poster_path": "/9i3plLl89DHMz7mahksDaAo7HIS.jpg",
    "popularity": 23.273,
    "vote_count": 11189,
    "video": false,
    "media_type": "movie",
    "id": 329,
    "adult": false,
    "backdrop_path": "/8I877mjRxFGfGAknIjF2Bv7tbyO.jpg",
    "original_language": "en",
    "original_title": "Jurassic Park",
    "genre_ids": [12, 878],
    "title": "Jurassic Park",
    "vote_average": 7.9,
    "overview":
        "A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA. Before opening day, he invites a team of experts and his two eager grandchildren to experience the park and help calm anxious investors. However, the park is anything but amusing as the security systems go off-line and the dinosaurs escape.",
    "release_date": "1993-06-11"
  },
  {
    "poster_path": "/wcJFUcbPfXJRXRNXNFfF0W6dpx.jpg",
    "popularity": 40.908,
    "vote_count": 8472,
    "video": false,
    "media_type": "movie",
    "id": 280,
    "adult": false,
    "backdrop_path": "/pC9vQ5miLgdHSPIsgfU5A9pcTpF.jpg",
    "original_language": "en",
    "original_title": "Terminator 2: Judgment Day",
    "genre_ids": [28, 878, 53],
    "title": "Terminator 2: Judgment Day",
    "vote_average": 8,
    "overview":
        "Nearly 10 years have passed since Sarah Connor was targeted for termination by a cyborg from the future. Now her son, John, the future leader of the resistance, is the target for a newer, more deadly terminator. Once again, the resistance has managed to send a protector back to attempt to save John and his mother Sarah.",
    "release_date": "1991-07-03"
  },
  {
    "poster_path": "/t7xhP8SQTVanzecvn1oQRVWCXTI.jpg",
    "popularity": 35.33,
    "vote_count": 10282,
    "video": false,
    "media_type": "movie",
    "id": 424,
    "adult": false,
    "backdrop_path": "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
    "original_language": "en",
    "original_title": "Schindler's List",
    "genre_ids": [18, 36, 10752],
    "title": "Schindler's List",
    "vote_average": 8.6,
    "overview":
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    "release_date": "1993-11-30"
  },
  {
    "vote_count": 20044,
    "popularity": 43.869,
    "id": 550,
    "video": false,
    "media_type": "movie",
    "vote_average": 8.4,
    "title": "Fight Club",
    "release_date": "1999-10-15",
    "original_language": "en",
    "original_title": "Fight Club",
    "genre_ids": [18],
    "backdrop_path": "/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg",
    "adult": false,
    "overview":
        "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
    "poster_path": "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg"
  },
  {
    "poster_path": "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
    "popularity": 50.033,
    "vote_count": 12916,
    "video": false,
    "media_type": "movie",
    "id": 862,
    "adult": false,
    "backdrop_path": "/lxD5ak7BOoinRNehOCA85CQ8ubr.jpg",
    "original_language": "en",
    "original_title": "Toy Story",
    "genre_ids": [16, 35, 10751],
    "title": "Toy Story",
    "vote_average": 7.9,
    "overview":
        "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",
    "release_date": "1995-10-30"
  },
  {
    "poster_path": "/wby9315QzVKdW9BonAefg8jGTTb.jpg",
    "popularity": 31.489,
    "vote_count": 8393,
    "video": false,
    "media_type": "movie",
    "id": 14,
    "adult": false,
    "backdrop_path": "/DztBnZaqmla2sGUW9s8AyOmskT.jpg",
    "original_language": "en",
    "original_title": "American Beauty",
    "genre_ids": [18],
    "title": "American Beauty",
    "vote_average": 8,
    "overview":
        "Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation with his daughter's attractive friend.",
    "release_date": "1999-09-15"
  },
  {
    "vote_count": 13732,
    "popularity": 44.304,
    "id": 807,
    "video": false,
    "media_type": "movie",
    "vote_average": 8.3,
    "title": "Se7en",
    "release_date": "1995-09-22",
    "original_language": "en",
    "original_title": "Se7en",
    "genre_ids": [80, 9648, 53],
    "backdrop_path": "/4U4q1zjIwCZTNkp6RKWkWPuC7uI.jpg",
    "adult": false,
    "overview":
        "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the \"seven deadly sins\" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer's mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.",
    "poster_path": "/6yoghtyTpznpBik8EngEmJskVUO.jpg"
  },
  {
    "vote_count": 6735,
    "popularity": 31.096,
    "id": 602,
    "video": false,
    "media_type": "movie",
    "vote_average": 6.8,
    "title": "Independence Day",
    "release_date": "1996-06-25",
    "original_language": "en",
    "original_title": "Independence Day",
    "genre_ids": [28, 12, 878],
    "backdrop_path": "/uw4SnKFZ453Gxmj5XR5Susj8TNo.jpg",
    "adult": false,
    "overview":
        "On July 2, a giant alien mothership enters orbit around Earth and deploys several dozen saucer-shaped 'destroyer' spacecraft that quickly lay waste to major cities around the planet. On July 3, the United States conducts a coordinated counterattack that fails. On July 4, a plan is devised to gain access to the interior of the alien mothership in space, in order to plant a nuclear missile.",
    "poster_path": "/p0BPQGSPoSa8Ml0DAf2mB2kCU0R.jpg"
  },
  {
    "poster_path": "/oYUZHYMwNKnE1ef4WE5Hw2a9OAY.jpg",
    "popularity": 19.8,
    "vote_count": 3676,
    "video": false,
    "media_type": "movie",
    "id": 568,
    "adult": false,
    "backdrop_path": "/AfGp6Ev3BVdEd7L99kGQzOzsqRb.jpg",
    "original_language": "en",
    "original_title": "Apollo 13",
    "genre_ids": [18, 36],
    "title": "Apollo 13",
    "vote_average": 7.4,
    "overview":
        "The true story of technical troubles that scuttle the Apollo 13 lunar mission in 1970, risking the lives of astronaut Jim Lovell and his crew, with the failed journey turning into a thrilling saga of heroism. Drifting more than 200,000 miles from Earth, the astronauts work furiously with the ground crew to avert tragedy.",
    "release_date": "1995-06-30"
  },
  {
    "poster_path": "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    "popularity": 41.356,
    "vote_count": 12940,
    "video": false,
    "media_type": "movie",
    "id": 238,
    "adult": false,
    "backdrop_path": "/41xIKcLiM5ryfz4C9sZFcBOJGsK.jpg",
    "original_language": "en",
    "original_title": "The Godfather",
    "genre_ids": [80, 18],
    "title": "The Godfather",
    "vote_average": 8.7,
    "overview":
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    "release_date": "1972-03-14"
  },
  {
    "poster_path": "/eOFjZMYYx9T8JuV0gm2ezEw0rdl.jpg",
    "popularity": 20.595,
    "vote_count": 2684,
    "video": false,
    "media_type": "movie",
    "id": 5503,
    "adult": false,
    "backdrop_path": "/sdylVXKmMZb5nCRJiMUwfDzVDQJ.jpg",
    "original_language": "en",
    "original_title": "The Fugitive",
    "genre_ids": [28, 12, 80, 9648, 53],
    "title": "The Fugitive",
    "vote_average": 7.4,
    "overview":
        "Wrongfully convicted of murdering his wife and sentenced to death, Richard Kimble escapes from the law in an attempt to find her killer and clear his name. Pursuing him is a team of U.S. marshals led by Deputy Samuel Gerard, a determined detective who will not rest until Richard is captured. As Kimble leads the marshals through a series of intricate chases, he uncovers the secret behind his wife's death and struggles to expose the killer before he is recaptured, or killed.",
    "release_date": "1993-08-06"
  },
  {
    "poster_path": "/lH3dsbxA4wLalWKNYpVldX8zfPP.jpg",
    "popularity": 45.42,
    "vote_count": 4993,
    "video": false,
    "media_type": "movie",
    "id": 268,
    "adult": false,
    "backdrop_path": "/2va32apQP97gvUxaMnL5wYt4CRB.jpg",
    "original_language": "en",
    "original_title": "Batman",
    "genre_ids": [28, 14],
    "title": "Batman",
    "vote_average": 7.2,
    "overview":
        "Having witnessed his parents' brutal murder as a child, millionaire philanthropist Bruce Wayne fights crime in Gotham City disguised as Batman, a costumed hero who strikes fear into the hearts of villains. But when a deformed madman who calls himself \"The Joker\" seizes control of Gotham's criminal underworld, Batman must face his most ruthless nemesis ever while protecting both his identity and his love interest, reporter Vicki Vale.",
    "release_date": "1989-06-23"
  },
  {
    "poster_path": "/1wY4psJ5NVEhCuOYROwLH2XExM2.jpg",
    "popularity": 36.797,
    "vote_count": 10750,
    "video": false,
    "media_type": "movie",
    "id": 857,
    "adult": false,
    "backdrop_path": "/hjQp148VjWF4KjzhsD90OCMr11h.jpg",
    "original_language": "en",
    "original_title": "Saving Private Ryan",
    "genre_ids": [18, 36, 10752],
    "title": "Saving Private Ryan",
    "vote_average": 8.1,
    "overview":
        "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.",
    "release_date": "1998-07-24"
  },
  {
    "poster_path": "/eLFfl7vS8dkeG1hKp5mwbm37V83.jpg",
    "popularity": 43.259,
    "vote_count": 8240,
    "video": false,
    "media_type": "movie",
    "id": 812,
    "adult": false,
    "backdrop_path": "/5OeY4U2rzePxWq2rkqMajUx2gz7.jpg",
    "original_language": "en",
    "original_title": "Aladdin",
    "genre_ids": [12, 16, 14, 10749, 10751],
    "title": "Aladdin",
    "vote_average": 7.6,
    "overview":
        "Princess Jasmine grows tired of being forced to remain in the palace, so she sneaks out into the marketplace, in disguise, where she meets street-urchin Aladdin.  The couple falls in love, although Jasmine may only marry a prince.  After being thrown in jail, Aladdin becomes embroiled in a plot to find a mysterious lamp, with which the evil Jafar hopes to rule the land.",
    "release_date": "1992-11-25"
  },
  {
    "vote_count": 5033,
    "popularity": 23.777,
    "id": 275,
    "video": false,
    "media_type": "movie",
    "vote_average": 7.9,
    "title": "Fargo",
    "release_date": "1996-03-08",
    "original_language": "en",
    "original_title": "Fargo",
    "genre_ids": [80, 18, 53],
    "backdrop_path": "/747dgDfL5d8esobk7h4odaOFhUq.jpg",
    "adult": false,
    "overview":
        "Jerry, a small-town Minnesota car salesman is bursting at the seams with debt... but he's got a plan. He's going to hire two thugs to kidnap his wife in a scheme to collect a hefty ransom from his wealthy father-in-law. It's going to be a snap and nobody's going to get hurt... until people start dying. Enter Police Chief Marge, a coffee-drinking, parka-wearing - and extremely pregnant - investigator who'll stop at nothing to get her man. And if you think her small-time investigative skills will give the crooks a run for their ransom... you betcha!",
    "poster_path": "/9lyml7x9W2RpXCMGCuspPO11tSY.jpg"
  },
  {
    "vote_count": 7846,
    "popularity": 28.559,
    "id": 745,
    "video": false,
    "media_type": "movie",
    "vote_average": 7.9,
    "title": "The Sixth Sense",
    "release_date": "1999-08-06",
    "original_language": "en",
    "original_title": "The Sixth Sense",
    "genre_ids": [9648, 53, 18],
    "backdrop_path": "/6TjllWT3cGrPFyqDXurVZ3L8bBi.jpg",
    "adult": false,
    "overview":
        "A psychological thriller about an eight year old boy named Cole Sear who believes he can see into the world of the dead. A child psychologist named Malcolm Crowe comes to Cole to help him deal with his problem, learning that he really can see the ghosts of dead people.",
    "poster_path": "/fIssD3w3SvIhPPmVo4WMgZDVLID.jpg"
  },
  {
    "vote_count": 2554,
    "popularity": 27.131,
    "id": 36955,
    "video": false,
    "media_type": "movie",
    "vote_average": 7,
    "title": "True Lies",
    "release_date": "1994-07-15",
    "original_language": "en",
    "original_title": "True Lies",
    "genre_ids": [28, 53],
    "backdrop_path": "/f1rLtbh72vzcHFzJJeCcHAUUXK8.jpg",
    "adult": false,
    "overview":
        "A fearless, globe-trotting, terrorist-battling secret agent has his life turned upside down when he discovers his wife might be having an affair with a used car salesman while terrorists smuggle nuclear war heads into the United States.",
    "poster_path": "/9yOzwgGdVoRhDYSwVbhyhgNMoUi.jpg"
  },
  {
    "vote_count": 5470,
    "popularity": 28.83,
    "id": 63,
    "video": false,
    "media_type": "movie",
    "vote_average": 7.6,
    "title": "Twelve Monkeys",
    "release_date": "1995-12-29",
    "original_language": "en",
    "original_title": "Twelve Monkeys",
    "genre_ids": [878, 53, 9648],
    "backdrop_path": "/2aPrheKAOwyjJqu6YYd2TvsKv9a.jpg",
    "adult": false,
    "overview":
        "In the year 2035, convict James Cole reluctantly volunteers to be sent back in time to discover the origin of a deadly virus that wiped out nearly all of the earth's population and forced the survivors into underground communities. But when Cole is mistakenly sent to 1990 instead of 1996, he's arrested and locked up in a mental hospital. There he meets psychiatrist Dr. Kathryn Railly, and patient Jeffrey Goines, the son of a famous virus expert, who may hold the key to the mysterious rogue group, the Army of the 12 Monkeys, thought to be responsible for unleashing the killer disease.",
    "poster_path": "/kKoG0hXBmBbkDnJYhhHisdin73W.jpg"
  },
  {
    "poster_path": "/7lyBcpYB0Qt8gYhXYaEZUNlNQAv.jpg",
    "popularity": 43.511,
    "vote_count": 13797,
    "video": false,
    "media_type": "movie",
    "id": 105,
    "adult": false,
    "backdrop_path": "/fq3wyOs1RHyz2yfzsb4sck7aWRG.jpg",
    "original_language": "en",
    "original_title": "Back to the Future",
    "genre_ids": [12, 35, 878, 10751],
    "title": "Back to the Future",
    "vote_average": 8.3,
    "overview":
        "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
    "release_date": "1985-07-03"
  },
  {
    "poster_path": "/pRn3TJHbAqCAO6U8Dw5DayVUuX3.jpg",
    "popularity": 47.582,
    "vote_count": 12399,
    "video": false,
    "media_type": "movie",
    "id": 98,
    "adult": false,
    "backdrop_path": "/aZtwH3RQ0L8jbInxr7OSc9tlGMJ.jpg",
    "original_language": "en",
    "original_title": "Gladiator",
    "genre_ids": [28, 12, 18],
    "title": "Gladiator",
    "vote_average": 8.2,
    "overview":
        "In the year 180, the death of emperor Marcus Aurelius throws the Roman Empire into chaos.  Maximus is one of the Roman army's most capable and trusted generals and a key advisor to the emperor.  As Marcus' devious son Commodus ascends to the throne, Maximus is set to be executed.  He escapes, but is captured by slave traders.  Renamed Spaniard and forced to become a gladiator, Maximus must battle to the death with other men for the amusement of paying audiences.",
    "release_date": "2000-05-01"
  }
];
